CreateConVar("acf_conquest_enable", 1, FCVAR_ARCHIVE + FCVAR_REPLICATED + FCVAR_NOTIFY, "Enables the ACF Conquest Gamemode.")
CreateConVar("acf_conquest_enable_bots", 1, FCVAR_ARCHIVE + FCVAR_REPLICATED + FCVAR_NOTIFY, "Enables bot spawning.")
CreateConVar("acf_conquest_max_bots", 15, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Defines the maximum amount of bots per team.")
CreateConVar("acf_conquest_max_tickets", 500, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Defines the amount of tickets each team starts with.")
CreateConVar("acf_conquest_min_players", 4, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Defines the minimal amount of players needed to start a game.")